apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://crystal-production-postgres.cxg882a6uzlh.ap-south-1.rds.amazonaws.com:5432/ledger-db?sslmode=require"
